const Districts = [
  { district: 'Anantapur', stateId: 1 },
  { district: 'Chittoor', stateId: 1 },
  { district: 'East Godavari', stateId: 1 },
  { district: 'Guntur', stateId: 1 },
  { district: 'Krishna', stateId: 1 },
  { district: 'Kurnool', stateId: 1 },
  { district: 'Prakasam', stateId: 1 },
  { district: 'Srikakulam', stateId: 1 },
  { district: 'Visakhapatnam', stateId: 1 },
  { district: 'Vizianagaram', stateId: 1 },
  { district: 'West Godavari', stateId: 1 },
  { district: 'YSR Kadapa', stateId: 1 },

  { district: 'Tawang', stateId: 2 },
  { district: 'West Kameng', stateId: 2 },
  { district: 'East Kameng', stateId: 2 },
  { district: 'Papum Pare', stateId: 2 },
  { district: 'Kurung Kumey', stateId: 2 },
  { district: 'Kra Daadi', stateId: 2 },
  { district: 'Lower Subansiri', stateId: 2 },
  { district: 'Upper Subansiri', stateId: 2 },
  { district: 'West Siang', stateId: 2 },
  { district: 'East Siang', stateId: 2 },
  { district: 'Siang', stateId: 2 },
  { district: 'Upper Siang', stateId: 2 },
  { district: 'Lower Siang', stateId: 2 },
  { district: 'Lower Dibang Valley', stateId: 2 },
  { district: 'Dibang Valley', stateId: 2 },
  { district: 'Anjaw', stateId: 2 },
  { district: 'Lohit', stateId: 2 },
  { district: 'Namsai', stateId: 2 },
  { district: 'Changlang', stateId: 2 },
  { district: 'Tirap', stateId: 2 },
  { district: 'Longding', stateId: 2 },

  { district: 'Baksa', stateId: 3 },
  { district: 'Barpeta', stateId: 3 },
  { district: 'Biswanath', stateId: 3 },
  { district: 'Bongaigaon', stateId: 3 },
  { district: 'Cachar', stateId: 3 },
  { district: 'Charaideo', stateId: 3 },
  { district: 'Chirang', stateId: 3 },
  { district: 'Darrang', stateId: 3 },
  { district: 'Dhemaji', stateId: 3 },
  { district: 'Dhubri', stateId: 3 },
  { district: 'Dibrugarh', stateId: 3 },
  { district: 'Dima Hasao', stateId: 3 },
  { district: 'Goalpara', stateId: 3 },
  { district: 'Golaghat', stateId: 3 },
  { district: 'Hailakandi', stateId: 3 },
  { district: 'Hojai', stateId: 3 },
  { district: 'Jorhat', stateId: 3 },
  { district: 'Kamrup', stateId: 3 },
  { district: 'Kamrup Metropolitan', stateId: 3 },
  { district: 'Karbi Anglong', stateId: 3 },
  { district: 'Karimganj', stateId: 3 },
  { district: 'Kokrajhar', stateId: 3 },
  { district: 'Lakhimpur', stateId: 3 },
  { district: 'Majuli', stateId: 3 },
  { district: 'Morigaon', stateId: 3 },
  { district: 'Nagaon', stateId: 3 },
  { district: 'Nalbari', stateId: 3 },
  { district: 'Sivasagar', stateId: 3 },
  { district: 'Sonitpur', stateId: 3 },
  { district: 'South Salmara-Mankachar', stateId: 3 },
  { district: 'Tinsukia', stateId: 3 },
  { district: 'Udalguri', stateId: 3 },
  { district: 'West Karbi Anglong', stateId: 3 },

  { district: 'Araria', stateId: 4 },
  { district: 'Arwal', stateId: 4 },
  { district: 'Aurangabad', stateId: 4 },
  { district: 'Banka', stateId: 4 },
  { district: 'Begusarai', stateId: 4 },
  { district: 'Bhagalpur', stateId: 4 },
  { district: 'Bhojpur', stateId: 4 },
  { district: 'Buxar', stateId: 4 },
  { district: 'Darbhanga', stateId: 4 },
  { district: 'East Champaran', stateId: 4 },
  { district: 'Gaya', stateId: 4 },
  { district: 'Gopalganj', stateId: 4 },
  { district: 'Jamui', stateId: 4 },
  { district: 'Jehanabad', stateId: 4 },
  { district: 'Kaimur', stateId: 4 },
  { district: 'Katihar', stateId: 4 },
  { district: 'Khagaria', stateId: 4 },
  { district: 'Kishanganj', stateId: 4 },
  { district: 'Lakhisarai', stateId: 4 },
  { district: 'Madhepura', stateId: 4 },
  { district: 'Madhubani', stateId: 4 },
  { district: 'Munger', stateId: 4 },
  { district: 'Muzaffarpur', stateId: 4 },
  { district: 'Nalanda', stateId: 4 },
  { district: 'Nawada', stateId: 4 },
  { district: 'Patna', stateId: 4 },
  { district: 'Purnia', stateId: 4 },
  { district: 'Rohtas', stateId: 4 },
  { district: 'Saharsa', stateId: 4 },
  { district: 'Samastipur', stateId: 4 },
  { district: 'Saran', stateId: 4 },
  { district: 'Sheikhpura', stateId: 4 },
  { district: 'Sheohar', stateId: 4 },
  { district: 'Sitamarhi', stateId: 4 },
  { district: 'Siwan', stateId: 4 },
  { district: 'Supaul', stateId: 4 },
  { district: 'Vaishali', stateId: 4 },
  { district: 'West Champaran', stateId: 4 },

  { district: 'Balod', stateId: 5 },
  { district: 'Baloda Bazar', stateId: 5 },
  { district: 'Balrampur', stateId: 5 },
  { district: 'Bastar', stateId: 5 },
  { district: 'Bemetara', stateId: 5 },
  { district: 'Bijapur', stateId: 5 },
  { district: 'Bilaspur', stateId: 5 },
  { district: 'Dantewada', stateId: 5 },
  { district: 'Dhamtari', stateId: 5 },
  { district: 'Durg', stateId: 5 },
  { district: 'Gariaband', stateId: 5 },
  { district: 'Janjgir-Champa', stateId: 5 },
  { district: 'Jashpur', stateId: 5 },
  { district: 'Kabirdham', stateId: 5 },
  { district: 'Kanker', stateId: 5 },
  { district: 'Kondagaon', stateId: 5 },
  { district: 'Korba', stateId: 5 },
  { district: 'Korea', stateId: 5 },
  { district: 'Mahasamund', stateId: 5 },
  { district: 'Mungeli', stateId: 5 },
  { district: 'Narayanpur', stateId: 5 },
  { district: 'Raigarh', stateId: 5 },
  { district: 'Raipur', stateId: 5 },
  { district: 'Rajnandgaon', stateId: 5 },
  { district: 'Sukma', stateId: 5 },
  { district: 'Surajpur', stateId: 5 },
  { district: 'Surguja', stateId: 5 },

  { district: 'North Goa', stateId: 6 },
  { district: 'South Goa', stateId: 6 },

  { district: 'Ahmedabad', stateId: 7 },
  { district: 'Amreli', stateId: 7 },
  { district: 'Anand', stateId: 7 },
  { district: 'Aravalli', stateId: 7 },
  { district: 'Banaskantha', stateId: 7 },
  { district: 'Bharuch', stateId: 7 },
  { district: 'Bhavnagar', stateId: 7 },
  { district: 'Botad', stateId: 7 },
  { district: 'Chhota Udaipur', stateId: 7 },
  { district: 'Dahod', stateId: 7 },
  { district: 'Dang', stateId: 7 },
  { district: 'Devbhoomi Dwarka', stateId: 7 },
  { district: 'Gandhinagar', stateId: 7 },
  { district: 'Gir Somnath', stateId: 7 },
  { district: 'Jamnagar', stateId: 7 },
  { district: 'Junagadh', stateId: 7 },
  { district: 'Kheda', stateId: 7 },
  { district: 'Kutch', stateId: 7 },
  { district: 'Mahisagar', stateId: 7 },
  { district: 'Mehsana', stateId: 7 },
  { district: 'Morbi', stateId: 7 },
  { district: 'Narmada', stateId: 7 },
  { district: 'Navsari', stateId: 7 },
  { district: 'Panchmahal', stateId: 7 },
  { district: 'Patan', stateId: 7 },
  { district: 'Porbandar', stateId: 7 },
  { district: 'Rajkot', stateId: 7 },
  { district: 'Sabarkantha', stateId: 7 },
  { district: 'Surat', stateId: 7 },
  { district: 'Surendranagar', stateId: 7 },
  { district: 'Tapi', stateId: 7 },
  { district: 'Vadodara', stateId: 7 },
  { district: 'Valsad', stateId: 7 },

  { district: 'Ambala', stateId: 8 },
  { district: 'Bhiwani', stateId: 8 },
  { district: 'Charkhi Dadri', stateId: 8 },
  { district: 'Faridabad', stateId: 8 },
  { district: 'Fatehabad', stateId: 8 },
  { district: 'Gurugram', stateId: 8 },
  { district: 'Hisar', stateId: 8 },
  { district: 'Jhajjar', stateId: 8 },
  { district: 'Jind', stateId: 8 },
  { district: 'Kaithal', stateId: 8 },
  { district: 'Karnal', stateId: 8 },
  { district: 'Kurukshetra', stateId: 8 },
  { district: 'Mahendragarh', stateId: 8 },
  { district: 'Nuh', stateId: 8 },
  { district: 'Palwal', stateId: 8 },
  { district: 'Panchkula', stateId: 8 },
  { district: 'Panipat', stateId: 8 },
  { district: 'Rewari', stateId: 8 },
  { district: 'Rohtak', stateId: 8 },
  { district: 'Sirsa', stateId: 8 },
  { district: 'Sonipat', stateId: 8 },
  { district: 'Yamunanagar', stateId: 8 },

  { district: 'Bilaspur', stateId: 9 },
  { district: 'Chamba', stateId: 9 },
  { district: 'Hamirpur', stateId: 9 },
  { district: 'Kangra', stateId: 9 },
  { district: 'Kinnaur', stateId: 9 },
  { district: 'Kullu', stateId: 9 },
  { district: 'Lahaul and Spiti', stateId: 9 },
  { district: 'Mandi', stateId: 9 },
  { district: 'Shimla', stateId: 9 },
  { district: 'Sirmaur', stateId: 9 },
  { district: 'Solan', stateId: 9 },
  { district: 'Una', stateId: 9 },

  { district: 'Bokaro', stateId: 10 },
  { district: 'Chatra', stateId: 10 },
  { district: 'Deoghar', stateId: 10 },
  { district: 'Dhanbad', stateId: 10 },
  { district: 'Dumka', stateId: 10 },
  { district: 'East Singhbhum', stateId: 10 },
  { district: 'Garhwa', stateId: 10 },
  { district: 'Giridih', stateId: 10 },
  { district: 'Godda', stateId: 10 },
  { district: 'Gumla', stateId: 10 },
  { district: 'Hazaribagh', stateId: 10 },
  { district: 'Jamtara', stateId: 10 },
  { district: 'Khunti', stateId: 10 },
  { district: 'Koderma', stateId: 10 },
  { district: 'Latehar', stateId: 10 },
  { district: 'Lohardaga', stateId: 10 },
  { district: 'Pakur', stateId: 10 },
  { district: 'Palamu', stateId: 10 },
  { district: 'Ramgarh', stateId: 10 },
  { district: 'Ranchi', stateId: 10 },
  { district: 'Sahebganj', stateId: 10 },
  { district: 'Seraikela Kharsawan', stateId: 10 },
  { district: 'Simdega', stateId: 10 },
  { district: 'West Singhbhum', stateId: 10 },

  { district: 'Bagalkot', stateId: 11 },
  { district: 'Ballari (Bellary)', stateId: 11 },
  { district: 'Belagavi (Belgaum)', stateId: 11 },
  { district: 'Bengaluru Rural', stateId: 11 },
  { district: 'Bengaluru Urban', stateId: 11 },
  { district: 'Bidar', stateId: 11 },
  { district: 'Chamarajanagar', stateId: 11 },
  { district: 'Chikballapur', stateId: 11 },
  { district: 'Chikkamagaluru (Chikmagalur)', stateId: 11 },
  { district: 'Chitradurga', stateId: 11 },
  { district: 'Dakshina Kannada', stateId: 11 },
  { district: 'Davanagere', stateId: 11 },
  { district: 'Dharwad', stateId: 11 },
  { district: 'Gadag', stateId: 11 },
  { district: 'Hassan', stateId: 11 },
  { district: 'Haveri', stateId: 11 },
  { district: 'Kalaburagi (Gulbarga)', stateId: 11 },
  { district: 'Kodagu (Coorg)', stateId: 11 },
  { district: 'Kolar', stateId: 11 },
  { district: 'Koppal', stateId: 11 },
  { district: 'Mandya', stateId: 11 },
  { district: 'Mysuru (Mysore)', stateId: 11 },
  { district: 'Raichur', stateId: 11 },
  { district: 'Ramanagara', stateId: 11 },
  { district: 'Shivamogga (Shimoga)', stateId: 11 },
  { district: 'Tumakuru (Tumkur)', stateId: 11 },
  { district: 'Udupi', stateId: 11 },
  { district: 'Uttara Kannada (Karwar)', stateId: 11 },
  { district: 'Vijayapura (Bijapur)', stateId: 11 },
  { district: 'Yadgir', stateId: 11 },

  { district: 'Alappuzha', stateId: 12 },
  { district: 'Ernakulam', stateId: 12 },
  { district: 'Idukki', stateId: 12 },
  { district: 'Kannur', stateId: 12 },
  { district: 'Kasaragod', stateId: 12 },
  { district: 'Kollam', stateId: 12 },
  { district: 'Kottayam', stateId: 12 },
  { district: 'Kozhikode', stateId: 12 },
  { district: 'Malappuram', stateId: 12 },
  { district: 'Palakkad', stateId: 12 },
  { district: 'Pathanamthitta', stateId: 12 },
  { district: 'Thiruvananthapuram', stateId: 12 },
  { district: 'Thrissur', stateId: 12 },
  { district: 'Wayanad', stateId: 12 },

  { district: 'Agar Malwa', stateId: 13 },
  { district: 'Alirajpur', stateId: 13 },
  { district: 'Anuppur', stateId: 13 },
  { district: 'Ashoknagar', stateId: 13 },
  { district: 'Balaghat', stateId: 13 },
  { district: 'Barwani', stateId: 13 },
  { district: 'Betul', stateId: 13 },
  { district: 'Bhind', stateId: 13 },
  { district: 'Bhopal', stateId: 13 },
  { district: 'Burhanpur', stateId: 13 },
  { district: 'Chhatarpur', stateId: 13 },
  { district: 'Chhindwara', stateId: 13 },
  { district: 'Damoh', stateId: 13 },
  { district: 'Datia', stateId: 13 },
  { district: 'Dewas', stateId: 13 },
  { district: 'Dhar', stateId: 13 },
  { district: 'Dindori', stateId: 13 },
  { district: 'Guna', stateId: 13 },
  { district: 'Gwalior', stateId: 13 },
  { district: 'Harda', stateId: 13 },
  { district: 'Hoshangabad', stateId: 13 },
  { district: 'Indore', stateId: 13 },
  { district: 'Jabalpur', stateId: 13 },
  { district: 'Jhabua', stateId: 13 },
  { district: 'Katni', stateId: 13 },
  { district: 'Khandwa', stateId: 13 },
  { district: 'Khargone', stateId: 13 },
  { district: 'Mandla', stateId: 13 },
  { district: 'Mandsaur', stateId: 13 },
  { district: 'Morena', stateId: 13 },
  { district: 'Narsinghpur', stateId: 13 },
  { district: 'Neemuch', stateId: 13 },
  { district: 'Panna', stateId: 13 },
  { district: 'Raisen', stateId: 13 },
  { district: 'Rajgarh', stateId: 13 },
  { district: 'Ratlam', stateId: 13 },
  { district: 'Rewa', stateId: 13 },
  { district: 'Sagar', stateId: 13 },
  { district: 'Satna', stateId: 13 },
  { district: 'Sehore', stateId: 13 },
  { district: 'Seoni', stateId: 13 },
  { district: 'Shahdol', stateId: 13 },
  { district: 'Shajapur', stateId: 13 },
  { district: 'Sheopur', stateId: 13 },
  { district: 'Shivpuri', stateId: 13 },
  { district: 'Sidhi', stateId: 13 },
  { district: 'Singrauli', stateId: 13 },
  { district: 'Tikamgarh', stateId: 13 },
  { district: 'Ujjain', stateId: 13 },
  { district: 'Umaria', stateId: 13 },
  { district: 'Vidisha', stateId: 13 },

  { district: 'Ahmednagar', stateId: 14 },
  { district: 'Akola', stateId: 14 },
  { district: 'Amravati', stateId: 14 },
  { district: 'Aurangabad', stateId: 14 },
  { district: 'Beed', stateId: 14 },
  { district: 'Bhandara', stateId: 14 },
  { district: 'Buldhana', stateId: 14 },
  { district: 'Chandrapur', stateId: 14 },
  { district: 'Dhule', stateId: 14 },
  { district: 'Gadchiroli', stateId: 14 },
  { district: 'Gondia', stateId: 14 },
  { district: 'Hingoli', stateId: 14 },
  { district: 'Jalgaon', stateId: 14 },
  { district: 'Jalna', stateId: 14 },
  { district: 'Kolhapur', stateId: 14 },
  { district: 'Latur', stateId: 14 },
  { district: 'Mumbai City', stateId: 14 },
  { district: 'Mumbai Suburban', stateId: 14 },
  { district: 'Nagpur', stateId: 14 },
  { district: 'Nanded', stateId: 14 },
  { district: 'Nandurbar', stateId: 14 },
  { district: 'Nashik', stateId: 14 },
  { district: 'Osmanabad', stateId: 14 },
  { district: 'Palghar', stateId: 14 },
  { district: 'Parbhani', stateId: 14 },
  { district: 'Pune', stateId: 14 },
  { district: 'Raigad', stateId: 14 },
  { district: 'Ratnagiri', stateId: 14 },
  { district: 'Sangli', stateId: 14 },
  { district: 'Satara', stateId: 14 },
  { district: 'Sindhudurg', stateId: 14 },
  { district: 'Solapur', stateId: 14 },
  { district: 'Thane', stateId: 14 },
  { district: 'Wardha', stateId: 14 },
  { district: 'Washim', stateId: 14 },
  { district: 'Yavatmal', stateId: 14 },

  { district: 'Bishnupur', stateId: 15 },
  { district: 'Chandel', stateId: 15 },
  { district: 'Churachandpur', stateId: 15 },
  { district: 'Imphal East', stateId: 15 },
  { district: 'Imphal West', stateId: 15 },
  { district: 'Jiribam', stateId: 15 },
  { district: 'Kakching', stateId: 15 },
  { district: 'Kamjong', stateId: 15 },
  { district: 'Kangpokpi', stateId: 15 },
  { district: 'Noney', stateId: 15 },
  { district: 'Pherzawl', stateId: 15 },
  { district: 'Senapati', stateId: 15 },
  { district: 'Tamenglong', stateId: 15 },
  { district: 'Tengnoupal', stateId: 15 },
  { district: 'Thoubal', stateId: 15 },
  { district: 'Ukhrul', stateId: 15 },

  { district: 'East Garo Hills', stateId: 16 },
  { district: 'East Jaintia Hills', stateId: 16 },
  { district: 'East Khasi Hills', stateId: 16 },
  { district: 'North Garo Hills', stateId: 16 },
  { district: 'Ribhoi', stateId: 16 },
  { district: 'South Garo Hills', stateId: 16 },
  { district: 'South West Garo Hills', stateId: 16 },
  { district: 'South West Khasi Hills', stateId: 16 },
  { district: 'West Garo Hills', stateId: 16 },
  { district: 'West Jaintia Hills', stateId: 16 },
  { district: 'West Khasi Hills', stateId: 16 },

  { district: 'Aizawl', stateId: 17 },
  { district: 'Champhai', stateId: 17 },
  { district: 'Hnahthial', stateId: 17 },
  { district: 'Khawzawl', stateId: 17 },
  { district: 'Kolasib', stateId: 17 },
  { district: 'Lawngtlai', stateId: 17 },
  { district: 'Lunglei', stateId: 17 },
  { district: 'Mamit', stateId: 17 },
  { district: 'Saiha', stateId: 17 },
  { district: 'Saitual', stateId: 17 },
  { district: 'Serchhip', stateId: 17 },

  { district: 'Dimapur', stateId: 18 },
  { district: 'Kiphire', stateId: 18 },
  { district: 'Kohima', stateId: 18 },
  { district: 'Longleng', stateId: 18 },
  { district: 'Mokokchung', stateId: 18 },
  { district: 'Mon', stateId: 18 },
  { district: 'Peren', stateId: 18 },
  { district: 'Phek', stateId: 18 },
  { district: 'Tuensang', stateId: 18 },
  { district: 'Wokha', stateId: 18 },
  { district: 'Zunheboto', stateId: 18 },

  { district: 'Angul', stateId: 19 },
  { district: 'Balangir', stateId: 19 },
  { district: 'Balasore', stateId: 19 },
  { district: 'Bargarh', stateId: 19 },
  { district: 'Bhadrak', stateId: 19 },
  { district: 'Boudh', stateId: 19 },
  { district: 'Cuttack', stateId: 19 },
  { district: 'Deogarh', stateId: 19 },
  { district: 'Dhenkanal', stateId: 19 },
  { district: 'Gajapati', stateId: 19 },
  { district: 'Ganjam', stateId: 19 },
  { district: 'Jagatsinghpur', stateId: 19 },
  { district: 'Jajpur', stateId: 19 },
  { district: 'Jharsuguda', stateId: 19 },
  { district: 'Kalahandi', stateId: 19 },
  { district: 'Kandhamal', stateId: 19 },
  { district: 'Kendrapara', stateId: 19 },
  { district: 'Kendujhar (Keonjhar)', stateId: 19 },
  { district: 'Khordha', stateId: 19 },
  { district: 'Koraput', stateId: 19 },
  { district: 'Malkangiri', stateId: 19 },
  { district: 'Mayurbhanj', stateId: 19 },
  { district: 'Nabarangpur', stateId: 19 },
  { district: 'Nayagarh', stateId: 19 },
  { district: 'Nuapada', stateId: 19 },
  { district: 'Puri', stateId: 19 },
  { district: 'Rayagada', stateId: 19 },
  { district: 'Sambalpur', stateId: 19 },
  { district: 'Subarnapur', stateId: 19 },
  { district: 'Sundargarh', stateId: 19 },

  { district: 'Amritsar', stateId: 20 },
  { district: 'Barnala', stateId: 20 },
  { district: 'Bathinda', stateId: 20 },
  { district: 'Faridkot', stateId: 20 },
  { district: 'Fatehgarh Sahib', stateId: 20 },
  { district: 'Fazilka', stateId: 20 },
  { district: 'Ferozepur', stateId: 20 },
  { district: 'Gurdaspur', stateId: 20 },
  { district: 'Hoshiarpur', stateId: 20 },
  { district: 'Jalandhar', stateId: 20 },
  { district: 'Kapurthala', stateId: 20 },
  { district: 'Ludhiana', stateId: 20 },
  { district: 'Mansa', stateId: 20 },
  { district: 'Moga', stateId: 20 },
  { district: 'Pathankot', stateId: 20 },
  { district: 'Patiala', stateId: 20 },
  { district: 'Rupnagar', stateId: 20 },
  { district: 'Sahibzada Ajit Singh Nagar', stateId: 20 },
  { district: 'Sangrur', stateId: 20 },
  { district: 'Tarn Taran', stateId: 20 },

  { district: 'Ajmer', stateId: 21 },
  { district: 'Alwar', stateId: 21 },
  { district: 'Banswara', stateId: 21 },
  { district: 'Baran', stateId: 21 },
  { district: 'Barmer', stateId: 21 },
  { district: 'Bharatpur', stateId: 21 },
  { district: 'Bhilwara', stateId: 21 },
  { district: 'Bikaner', stateId: 21 },
  { district: 'Bundi', stateId: 21 },
  { district: 'Chittorgarh', stateId: 21 },
  { district: 'Churu', stateId: 21 },
  { district: 'Dausa', stateId: 21 },
  { district: 'Dholpur', stateId: 21 },
  { district: 'Dungarpur', stateId: 21 },
  { district: 'Hanumangarh', stateId: 21 },
  { district: 'Jaipur', stateId: 21 },
  { district: 'Jaisalmer', stateId: 21 },
  { district: 'Jalore', stateId: 21 },
  { district: 'Jhalawar', stateId: 21 },
  { district: 'Jhunjhunu', stateId: 21 },
  { district: 'Jodhpur', stateId: 21 },
  { district: 'Karauli', stateId: 21 },
  { district: 'Kota', stateId: 21 },
  { district: 'Nagaur', stateId: 21 },
  { district: 'Pali', stateId: 21 },
  { district: 'Pratapgarh', stateId: 21 },
  { district: 'Rajsamand', stateId: 21 },
  { district: 'Sawai Madhopur', stateId: 21 },
  { district: 'Sikar', stateId: 21 },
  { district: 'Sirohi', stateId: 21 },
  { district: 'Sri Ganganagar', stateId: 21 },
  { district: 'Tonk', stateId: 21 },
  { district: 'Udaipur', stateId: 21 },

  { district: 'East Sikkim', stateId: 22 },
  { district: 'North Sikkim', stateId: 22 },
  { district: 'South Sikkim', stateId: 22 },
  { district: 'West Sikkim', stateId: 22 },

  { district: 'Ariyalur', stateId: 23 },
  { district: 'Chengalpattu', stateId: 23 },
  { district: 'Chennai', stateId: 23 },
  { district: 'Coimbatore', stateId: 23 },
  { district: 'Cuddalore', stateId: 23 },
  { district: 'Dharmapuri', stateId: 23 },
  { district: 'Dindigul', stateId: 23 },
  { district: 'Erode', stateId: 23 },
  { district: 'Kallakurichi', stateId: 23 },
  { district: 'Kancheepuram', stateId: 23 },
  { district: 'Kanyakumari', stateId: 23 },
  { district: 'Karur', stateId: 23 },
  { district: 'Krishnagiri', stateId: 23 },
  { district: 'Madurai', stateId: 23 },
  { district: 'Nagapattinam', stateId: 23 },
  { district: 'Namakkal', stateId: 23 },
  { district: 'Nilgiris', stateId: 23 },
  { district: 'Perambalur', stateId: 23 },
  { district: 'Pudukkottai', stateId: 23 },
  { district: 'Ramanathapuram', stateId: 23 },
  { district: 'Ranipet', stateId: 23 },
  { district: 'Salem', stateId: 23 },
  { district: 'Sivaganga', stateId: 23 },
  { district: 'Tenkasi', stateId: 23 },
  { district: 'Thanjavur', stateId: 23 },
  { district: 'Theni', stateId: 23 },
  { district: 'Thoothukudi', stateId: 23 },
  { district: 'Tiruchirappalli', stateId: 23 },
  { district: 'Tirunelveli', stateId: 23 },
  { district: 'Tirupathur', stateId: 23 },
  { district: 'Tiruppur', stateId: 23 },
  { district: 'Tiruvallur', stateId: 23 },
  { district: 'Tiruvannamalai', stateId: 23 },
  { district: 'Tiruvarur', stateId: 23 },
  { district: 'Vellore', stateId: 23 },
  { district: 'Viluppuram', stateId: 23 },
  { district: 'Virudhunagar', stateId: 23 },

  { district: 'Adilabad', stateId: 24 },
  { district: 'Bhadradri Kothagudem', stateId: 24 },
  { district: 'Hyderabad', stateId: 24 },
  { district: 'Jagtial', stateId: 24 },
  { district: 'Jangaon', stateId: 24 },
  { district: 'Jayashankar Bhupalpally', stateId: 24 },
  { district: 'Jogulamba Gadwal', stateId: 24 },
  { district: 'Kamareddy', stateId: 24 },
  { district: 'Karimnagar', stateId: 24 },
  { district: 'Khammam', stateId: 24 },
  { district: 'Komaram Bheem', stateId: 24 },
  { district: 'Mahabubabad', stateId: 24 },
  { district: 'Mahabubnagar', stateId: 24 },
  { district: 'Mancherial', stateId: 24 },
  { district: 'Medak', stateId: 24 },
  { district: 'Medchal–Malkajgiri', stateId: 24 },
  { district: 'Nagarkurnool', stateId: 24 },
  { district: 'Nalgonda', stateId: 24 },
  { district: 'Nirmal', stateId: 24 },
  { district: 'Nizamabad', stateId: 24 },
  { district: 'Peddapalli', stateId: 24 },
  { district: 'Rajanna Sircilla', stateId: 24 },
  { district: 'Rangareddy', stateId: 24 },
  { district: 'Sangareddy', stateId: 24 },
  { district: 'Siddipet', stateId: 24 },
  { district: 'Suryapet', stateId: 24 },
  { district: 'Vikarabad', stateId: 24 },
  { district: 'Wanaparthy', stateId: 24 },
  { district: 'Warangal Rural', stateId: 24 },
  { district: 'Warangal Urban', stateId: 24 },
  { district: 'Yadadri Bhuvanagiri', stateId: 24 },

  { district: 'Dhalai', stateId: 25 },
  { district: 'Gomati', stateId: 25 },
  { district: 'Khowai', stateId: 25 },
  { district: 'North Tripura', stateId: 25 },
  { district: 'Sepahijala', stateId: 25 },
  { district: 'South Tripura', stateId: 25 },
  { district: 'Unakoti', stateId: 25 },
  { district: 'West Tripura', stateId: 25 },

  { district: 'Agra', stateId: 26 },
  { district: 'Aligarh', stateId: 26 },
  { district: 'Ambedkar Nagar', stateId: 26 },
  { district: 'Amethi', stateId: 26 },
  { district: 'Amroha', stateId: 26 },
  { district: 'Auraiya', stateId: 26 },
  { district: 'Ayodhya', stateId: 26 },
  { district: 'Azamgarh', stateId: 26 },
  { district: 'Baghpat', stateId: 26 },
  { district: 'Bahraich', stateId: 26 },
  { district: 'Ballia', stateId: 26 },
  { district: 'Balrampur', stateId: 26 },
  { district: 'Banda', stateId: 26 },
  { district: 'Barabanki', stateId: 26 },
  { district: 'Bareilly', stateId: 26 },
  { district: 'Basti', stateId: 26 },
  { district: 'Bhadohi', stateId: 26 },
  { district: 'Bijnor', stateId: 26 },
  { district: 'Budaun', stateId: 26 },
  { district: 'Bulandshahr', stateId: 26 },
  { district: 'Chandauli', stateId: 26 },
  { district: 'Chitrakoot', stateId: 26 },
  { district: 'Deoria', stateId: 26 },
  { district: 'Etah', stateId: 26 },
  { district: 'Etawah', stateId: 26 },
  { district: 'Farrukhabad', stateId: 26 },
  { district: 'Fatehpur', stateId: 26 },
  { district: 'Firozabad', stateId: 26 },
  { district: 'Gautam Buddha Nagar', stateId: 26 },
  { district: 'Ghaziabad', stateId: 26 },
  { district: 'Ghazipur', stateId: 26 },
  { district: 'Gonda', stateId: 26 },
  { district: 'Gorakhpur', stateId: 26 },
  { district: 'Hamirpur', stateId: 26 },
  { district: 'Hapur', stateId: 26 },
  { district: 'Hardoi', stateId: 26 },
  { district: 'Hathras', stateId: 26 },
  { district: 'Jalaun', stateId: 26 },
  { district: 'Jaunpur', stateId: 26 },
  { district: 'Jhansi', stateId: 26 },
  { district: 'Kannauj', stateId: 26 },
  { district: 'Kanpur Dehat', stateId: 26 },
  { district: 'Kanpur Nagar', stateId: 26 },
  { district: 'Kasganj', stateId: 26 },
  { district: 'Kaushambi', stateId: 26 },
  { district: 'Kushinagar', stateId: 26 },
  { district: 'Lakhimpur Kheri', stateId: 26 },
  { district: 'Lalitpur', stateId: 26 },
  { district: 'Lucknow', stateId: 26 },
  { district: 'Maharajganj', stateId: 26 },
  { district: 'Mahoba', stateId: 26 },
  { district: 'Mainpuri', stateId: 26 },
  { district: 'Mathura', stateId: 26 },
  { district: 'Mau', stateId: 26 },
  { district: 'Meerut', stateId: 26 },
  { district: 'Mirzapur', stateId: 26 },
  { district: 'Moradabad', stateId: 26 },
  { district: 'Muzaffarnagar', stateId: 26 },
  { district: 'Pilibhit', stateId: 26 },
  { district: 'Pratapgarh', stateId: 26 },
  { district: 'Prayagraj', stateId: 26 },
  { district: 'Rae Bareli', stateId: 26 },
  { district: 'Rampur', stateId: 26 },
  { district: 'Saharanpur', stateId: 26 },
  { district: 'Sambhal', stateId: 26 },
  { district: 'Sant Kabir Nagar', stateId: 26 },
  { district: 'Shahjahanpur', stateId: 26 },
  { district: 'Shamli', stateId: 26 },
  { district: 'Shrawasti', stateId: 26 },
  { district: 'Siddharthnagar', stateId: 26 },
  { district: 'Sitapur', stateId: 26 },
  { district: 'Sonbhadra', stateId: 26 },
  { district: 'Sultanpur', stateId: 26 },
  { district: 'Unnao', stateId: 26 },
  { district: 'Varanasi', stateId: 26 },

  { district: 'Almora', stateId: 27 },
  { district: 'Bageshwar', stateId: 27 },
  { district: 'Chamoli', stateId: 27 },
  { district: 'Champawat', stateId: 27 },
  { district: 'Dehradun', stateId: 27 },
  { district: 'Haridwar', stateId: 27 },
  { district: 'Nainital', stateId: 27 },
  { district: 'Pauri Garhwal', stateId: 27 },
  { district: 'Pithoragarh', stateId: 27 },
  { district: 'Rudraprayag', stateId: 27 },
  { district: 'Tehri Garhwal', stateId: 27 },
  { district: 'Udham Singh Nagar', stateId: 27 },
  { district: 'Uttarkashi', stateId: 27 },

  { district: 'Alipurduar', stateId: 28 },
  { district: 'Bankura', stateId: 28 },
  { district: 'Birbhum', stateId: 28 },
  { district: 'Cooch Behar', stateId: 28 },
  { district: 'Dakshin Dinajpur (South Dinajpur)', stateId: 28 },
  { district: 'Darjeeling', stateId: 28 },
  { district: 'Hooghly', stateId: 28 },
  { district: 'Howrah', stateId: 28 },
  { district: 'Jalpaiguri', stateId: 28 },
  { district: 'Jhargram', stateId: 28 },
  { district: 'Kalimpong', stateId: 28 },
  { district: 'Kolkata', stateId: 28 },
  { district: 'Malda', stateId: 28 },
  { district: 'Murshidabad', stateId: 28 },
  { district: 'Nadia', stateId: 28 },
  { district: 'North 24 Parganas', stateId: 28 },
  { district: 'Paschim Bardhaman (West Bardhaman)', stateId: 28 },
  { district: 'Paschim Medinipur (West Medinipur)', stateId: 28 },
  { district: 'Purba Bardhaman (East Bardhaman)', stateId: 28 },
  { district: 'Purba Medinipur (East Medinipur)', stateId: 28 },
  { district: 'Purulia', stateId: 28 },
  { district: 'South 24 Parganas', stateId: 28 },
  { district: 'Uttar Dinajpur (North Dinajpur)', stateId: 28 },
];
export default Districts;
