BEGIN TRY

BEGIN TRAN;

-- AddForeignKey
ALTER TABLE [dbo].[SubscriptionMaster] ADD CONSTRAINT [SubscriptionMaster_userId_fkey] FOREIGN KEY ([userId]) REFERENCES [dbo].[UserMaster]([id]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
