BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[CampaignMaster] ALTER COLUMN [fromDate] NVARCHAR(1000) NOT NULL;
ALTER TABLE [dbo].[CampaignMaster] ALTER COLUMN [toDate] NVARCHAR(1000) NOT NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
